/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {  type: "category",
      label: "Components",
      items: [{type: 'autogenerated', dirName: 'components'}]
    },
    {
      type: "category",
      label: "Pages",
      items: [
        {
          type: "category",
          label: "User Authentication",
          items: ["pages/login-page", "pages/register-page", "pages/forgot-password-page"],
        },
        {
          type: "category",
          label: "Guest User",
          items: ["pages/free-services-page", "pages/service-inquiry-page", "pages/quote-request-page"],
        },
        {
          type: "category",
          label: "Client User",
          items: [
            "pages/service-catalog-page",
            "pages/filter-services-page",
            "pages/service-details-page",
            "pages/calculate-quote-page",
            "pages/request-quote-page",
            "pages/payment-details-page",
            "pages/order-details-page",
            "pages/my-tasks-page",
            "pages/task-progress-page",
          ],
        },
        {
          type: "category",
          label: "System Pages",
          items: [
            "pages/manage-services-page",
            "pages/payment-processing-page",
            "pages/order-processing-page",
            "pages/task-management-page",
            "pages/send-notifications-page",
          ],
        },
        {
          type: "category",
          label: "Databases",
          items: ["pages/user-database-page", "pages/service-database-page", "pages/quote-database-page", "pages/usage-database-page"],
        },
        {
          type: "doc",
          id: "pages/layout",
          label: "Layout",
        },
      ],
    },
  ],
};

export default sidebars;
